### ISSUE TITLE
TEKKIFY 3 Crash Report

### ISSUE THREAD

**Issue by Pr0xGaM3z** [Tekkify/Tekkify#10]
Note: I hit play, it does it thing, closes launcher keeping console, 5 seconds later: BAM! Crashes

Link: pastebin.com/tq1W1emg

**Comment by Nentify** [comment]
Please post your error log to pastebin

**Comment by Pr0xGaM3z** [comment]
Its on pastebin... It says a  link

**Comment by Nentify** [comment]
Try a fresh install of the modpack, otherwise I'm not sure. I'll have to look into it further. Pastebin the entire log again if you continue to crash.
