### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by pixelchicken** [Tekkify/Tekkify#11]
soo I thought i would tell you my side of things before i do the requirements. Before i could log on to tekkify alpha no problem, but not get on to single player hoping this would be fixed for the multiplayer server with all sorts of items disabled. today i notice tekkify has the update for the main 1.7.10 pack. i install it everything works out great. until i hit the mojang screen. thats when my computer just face planted a backflip and crashed. i tried getting on the alpha pack and the same thing happened again! please help me fix this..

Thanks 
             ~Pixel

In-Game Name: PixelChicken_PCF
Description of the Crash: Crash...
Operating System: windows 7, intel core i7, 32 bit
Java Version:8
Paste Bin/Crash Report (See Below): Main 1.7.10 modpack- paste.ubuntu.com/9695112/  Alpha modpack-  paste.ubuntu.com/9695116/
Can you run Singleplayer?: nope.. not even when i used to be able to log onto alpha
Solutions tried: Restarting

**Comment by Haidyn** [comment]
http://forums.tekkify.com/threads/tekkify-1-7-10-32-bit-computer-problems.4900/

Follow the steps here, you have an OutOfMemoryError crash.

**Comment by pixelchicken** [comment]
i posted that....

**Comment by pixelchicken** [comment]
i thought so to.. but it came back

**Comment by Nentify** [comment]
You'll need to try assigning more memory, don't put in java args, use the drop down menu. I can launch the page when it's set to 1GB.
