### ISSUE TITLE
Crash when placing down rusty hatch from Malisis' Doors

### ISSUE THREAD

**Issue by MeanTomatoes** [Tekkify/Tekkify#12]
Here's my log; can someone with a beefier computer confirm this? I was only doing so with my laptop.
http://paste.ubuntu.com/9710048/

**Comment by Haidyn** [comment]
Works fine for me.

**Comment by Nentify** [comment]
The developer has been made aware of the issue, thanks for the report.

**Comment by Nentify** [comment]
This has been fixed.
