### ISSUE TITLE
Non-lobby portals crash when a Thaumcraft wand is in the inventory

### ISSUE THREAD

**Issue by Sonicx00222** [Tekkify/Tekkify#16]
Crash report: pastebin.com/dxhi2PQ6
Non-lobby portals in this case mean portals that don't go to and from the lobby server.

EDIT: Looks like the crash only happens with the wand in the hotbar for whatever reason.

**Comment by Sonicx00222** [comment]
Looks like the crash only happens with the wand in the hotbar for whatever reason.

**Comment by Nentify** [comment]
Thanks - Will let users know if they are having this issue. We are actively looking for a solution for cross-server crashes.
