### ISSUE TITLE
Timed out issues

### ISSUE THREAD

**Issue by ywyak** [Tekkify/Tekkify#2]
In-game username:ywyak

Operating system:Win10
Java version: .java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

Crash log(s):Not needed, since i dont actually crash, but will post here: https://gist.github.com/ywyak/fb6d55a43cd508b5330c

Solution tried: 
*Manually removing .technic folder and reinstalling. 
*Increasing more ram space. 
*Tried to allow technic to firewall. failed because i could not find technic in firewall. 

I never had issues with tekkify and/or my internet. this all happened when Betorob got rolled back and when i actually updated to Win10. i would apprecieate if you give me instruction on how to remove those never ending timedout.

**Comment by Nentify** [comment]
What is this crash log?

**Comment by ywyak** [comment]
No idea, timing out never crashed for me, so i grabbed all crash log i can find, which happens to be only one.

**Comment by Nentify** [comment]
Does this occur anywhere on the map or a at a specific location?

**Comment by ywyak** [comment]
nope, its always random. yesterday i was timing out so much, now today i just got on fine without a hitch for first time.

**Comment by ywyak** [comment]
im gonna go ahead and assume you meant FML log, so here you go https://gist.github.com/ywyak/6b7b65ba7478c8baca3c

**Comment by ywyak** [comment]
also a latest log: https://gist.github.com/ywyak/c27e5015adfc5ed436a5

**Comment by ywyak** [comment]
another time out: FML: https://gist.github.com/ywyak/c2e9d771ea2803d3e23e

Latest: https://gist.github.com/ywyak/ceaef26486f900e0f59a

**Comment by ywyak** [comment]
another one: ditto furnance was really disabled.
latest:https://gist.github.com/ywyak/e67fa5c50ad15a8bcfb4
FML:https://gist.github.com/ywyak/394e2c6455f2472b2270

**Comment by ywyak** [comment]
after reporting the above, i played tekkify and crashed. here is crashlog: https://gist.github.com/ywyak/bdd9d0a9fc279b5ff273

**Comment by ywyak** [comment]
i had pretty fast timing out, it was my first time getting on Resources world, from what i see, its journey map. https://gist.github.com/ywyak/d94247914c8ce8979c39

**Comment by Nentify** [comment]
Have you tried running without JM?

**Comment by ywyak** [comment]
jar or folder?

**Comment by Nentify** [comment]
Jar

On 4 Aug 2015 10:58 pm, ywyak <notifications@github.com> wrote:
jar or folder?

---

**Comment by ywyak** [comment]
everytime i try to log in, instant timeout now. [Journeymap jar removed]

here is latest fml https://gist.github.com/ywyak/25e4f54a6267f4303907

**Comment by ywyak** [comment]
after relaunching technic, i was able to play fine. continue to fly around in Resources until i timed out.
Fml: https://gist.github.com/ywyak/536859cb681c0089ad0c
