### ISSUE TITLE
Idle kick 15mins - sends to lobby

### ISSUE THREAD

**Issue by eperdeme** [Tekkify/Tekkify#20]
Hello,

When kicked for idling for 15mins you are sent back to the lobby instead of back to the server you originated from.

[10:48:10] [Client thread/INFO]: [CHAT] [Kick] You have been kicked for idling more than 15 minutes.

Unsure if this is a bug or intended result.

Additionally, the error for being kicked for idling is also some text about scoreboard match errors, which does not make it clear why you got disconnected.

**Comment by Haidyn** [comment]
You are kicked from the player servers when afk for more than 15 minutes, AutoRank does not count time on the lobby which is why this is intended.
