### ISSUE TITLE
Other Saps banned

### ISSUE THREAD

**Issue by MommyNurse** [Tekkify/Tekkify#22]
I know that the Redwood Saplings were banned, but, I went to click "sort" on my chest that had my saplings (no redwood saps) in it, and it poofed my sakura saps and some others (not sure exactly which ones ;S.  So, to sum it up:  other saps (not just redwood) are giving the same "banned" message and reason that all mention "redwood."  Thanks :)

**Comment by Nentify** [comment]
This has since been fixed.
