### ISSUE TITLE
Claims Permission Spam

### ISSUE THREAD

**Issue by RawrImDragon** [Tekkify/Tekkify#23]
So on flux, if you find a place and so much as tap a claim it spams you with "you don't have x's permission to use that"
A single click usually results in it being said 3 times
(example: http://i.imgur.com/kWWByHR.png )
holding for any length of time continues this filling the entire chat with a huge amount of the same spam

**Comment by Nentify** [comment]
Don't touch it then!

**Comment by RawrImDragon** [comment]
Edit, it only happens with fence. also that's a solution to the spam, not to the issue xD

**Comment by Nentify** [comment]
The issue is the spam, is it not?

**Comment by Nentify** [comment]
Working as intended
