### ISSUE TITLE
Extra Cells Glitch

### ISSUE THREAD

**Issue by Gruur** [Tekkify/Tekkify#3]
Moved report to github @ Nent's request.
Single player mode. Mode pack 0.7.2.

The ME Fluid Terminal does not show liquids stored in tanks or drums until you click the import or export port in the GUI. 

I did a basic me system with energy cell, me controller, me drive with 1 me 1k liquid storage, me fluid terminal, me smart cable to 3 storage drums and 1 storage tank, using me fluid storage bus to connect the tanks to the me system.

I can add liquids to the system  through the GUI as normal and the system will always show the liquid that is stored in the drive. But the liquids in the tanks or drums (yes I know drums are banned in the new pack but was using them to get more familiar with the mod and used a hardened portable tank to verify glitch wasn't just with drums) will only show after I click on the import or export box in the gui, once I did that it would always show the contents until I log out. I'm unable to verify if it will glitch if the chunk is unloaded.

UPDATE
The above glitch wasn't present today, the exact same setup was still in my world and it didn't show the glitch. Go figure.

**Comment by Nentify** [comment]
Is this fixed then? I've also updated ExtraCells since then. Close ticket if all is good.
