### ISSUE TITLE
Unable to craft meatpacker

### ISSUE THREAD

**Issue by paulbatum** [Tekkify/Tekkify#31]
It requires a flux igniter which is disabled. I suggest you use minetweaker to change the recipe.

**Comment by Nentify** [comment]
Thanks, we'll add a new recipe for this.

**Comment by paulbatum** [comment]
Is this closed (fixed) or closed (won't fix)? I don't see any changes to the minetweaker recipies for MFR.

**Comment by Haidyn** [comment]
As of 3.0.8 
New recipe for meat packer (flux igniter replaced by flint and steel)

**Comment by paulbatum** [comment]
Sweet, thanks Haidyn! I'll try it the next time I'm online. 

I got confused because I thought I would see changes to the minetweaker scripts in the repo here.

**Comment by Haidyn** [comment]
Yeah I don't think Luke's pushing updates to git anymore, you can locate all changelogs for the pack in the announcement forums.
