### ISSUE TITLE
Ender IO Conduit Config Fix

### ISSUE THREAD

**Issue by Gruur** [Tekkify/Tekkify#4]
Moved report to github @ Nent's request.
modpack 0.7.2

I just noticed that the config file for Ender IO, needs a fix. For the fluid conduit it's set to 500mb/t extraction and max amount in the conduit is set to 200mb/t, That means that the pipe will hold less then 1/2 what it is capable of extracting. I believe you guys meant to set that to 2000mb/t to follow the other conduits in the mod. See line 266 bellow:

263     # Number of millibuckects per tick extracted by a fluid conduits auto extracting
264     I:fluidConduitExtractRate=500
265     # Number of millibuckects per tick that can pass through a single connection to a fluid conduit.
266     I:fluidConduitMaxIoRate=200

**Comment by Nentify** [comment]
Actually it appears an extra 0 was added to I:fluidConduitExtractRate, thanks.
