### ISSUE TITLE
NEI Use Crash

### ISSUE THREAD

**Issue by MeanTomatoes** [Tekkify/Tekkify#41]
With the help of Jazz we discovered that Waila caused a crash with NEI when pressing U on an item.

This needs more testing including another test on another system, a version without Waila but with the latest NEI (if it crashes we know it's actually NEI causing it, but if that's not the case), test NEI with 1.5.8  and 1.5.7a waila versions found here: http://www.curse.com/mc-mods/minecraft/waila#t1:other-downloads

**Comment by Haidyn** [comment]
#39

**Comment by MeanTomatoes** [comment]
Jazz's issue is different; he is crashing using the Waila block use feature, and this one is crashing with the NEI use feature.
