### ISSUE TITLE
Wither Skeletons in the Nether

### ISSUE THREAD

**Issue by DTA7** [Tekkify/Tekkify#42]
When I went to a nether fortress to get some wither skeleton skulls, I only found these, and many of them, but no normal wither skeletons:
![2015-01-30_14 39 09](https://cloud.githubusercontent.com/assets/10773525/5976425/d162aa82-a88d-11e4-968f-8a5a3bdf1c8e.png)
They also don't drop wither skeleton skulls (I killed many of them with a 70% beheading cleaver), only bones and arrows.

**Comment by darknife25** [comment]
This is a known bug in enderIO
CrazyPants/EnderIO/issues/1761

**Comment by Haidyn** [comment]
Waiting on a fix, they do drop skulls you must be more patient!
