### ISSUE TITLE
Dark steel helm with goggles of revealing sometimes doesn't reveal

### ISSUE THREAD

**Issue by Sonicx00222** [Tekkify/Tekkify#48]
Occasionally when wearing dark steel helms with the goggles of revealing upgrade, the goggles of revealing upgrade will stop working. Nodes become difficult to see again. Removing and putting on the helmet again does nothing. A normal pair of goggles of revealing still works as intended.

**Comment by ywyak** [comment]
there is toggle On and Off. Press R to turn Goggle of revealing.

useless feature in my opinion.

**Comment by Sonicx00222** [comment]
Thanks, can't believe I missed that.
