### ISSUE TITLE
MrCrayfish Furniture

### ISSUE THREAD

**Issue by Lycrios** [Tekkify/Tekkify#8]
Right clicking the computer from MrCrayfishes furniture mod causes an **instant** crash.

>[B#211]  -- Head --
[B#211]  Stacktrace:
[B#211]  	at com.mrcrayfish.furniture.gui.GuiComputer.func_146979_b(GuiComputer.java:147)
[B#211]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
[B#211]  	at com.mrcrayfish.furniture.gui.GuiComputer.func_73863_a(GuiComputer.java:175)

Find the error easier for the programmer:

>[B#211]  Description: Rendering screen
[B#211]  
[B#211]  java.lang.ArrayIndexOutOfBoundsException: 0
[B#211]  	at com.mrcrayfish.furniture.gui.GuiComputer.func_146979_b(GuiComputer.java:147)
[B#211]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
[B#211]  	at com.mrcrayfish.furniture.gui.GuiComputer.func_73863_a(GuiComputer.java:175)
[B#211]  	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
[B#211]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[B#211]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[B#211]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#211]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#211]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#211]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#211]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#211]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#211]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Nentify** [comment]
Reported to the developer, it's caused when there are no recipes in Minebay, so we may just have to enable 1 recipe temporarily.

**Comment by Nentify** [comment]
Fixed in latest update
