### ISSUE TITLE
TiC broadsword dungeon loot crash

### ISSUE THREAD

**Issue by Evan555alpha** [Tekkify/Tekkify#9]
I found a broadsword in a dungeon, and decided to try and use it. I was looking at some redwood from natura, and WAILA said that it was harvestable with it. Upon left clicking the redwood, I got an internal server error, thus my client crashed. The item's icon was a tad broken, too; http://puu.sh/eewHb/4a30f3cad6.jpg

Crash report(s); 
http://dpaste.com/38CP860 - client
http://dpaste.com/0JENMY8 - Server

**Comment by Nentify** [comment]
Updated TiC in the latest modpack version, could you see if it's fixed here? If not, I'll have to report it to the TiC developers.

**Comment by Rhah-** [comment]
Is this a world that was generated when we still had ITTweaks?
ITT adds randomly created weapons to dungeon loot. However there are some other mods that influence dungeon loot, that do not or cannot support NBT data on dungeon loot. If you encounter a colorful weird item in your dungeon loot, that's exactly what happened.
Known mods that cause this are: TooMuchLoot, DungeonPack

I know we have TML, or we had it at one point at least.
